#define NOMINMAX
#include <windows.h>
#include <d3d9.h>
#include <d3dcompiler.h>
#include <cassert>
#include <fstream>
#include <iterator>
#include <vector>
#include <cstdio>
#include <cmath>
#include "water_lamps_hlsl.h"
std::string ReadFile(const char* p){std::ifstream f(p,std::ios::binary);assert(f);return {std::istreambuf_iterator<char>(f),{}};}
ID3DBlob* Compile(const std::string& s,const char* target){ID3DBlob *b=nullptr,*e=nullptr;auto hr=D3DCompile(s.data(),s.size(),"water check",nullptr,nullptr,"main",target,D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b,&e);if(e){puts((char*)e->GetBufferPointer());e->Release();}assert(SUCCEEDED(hr));return b;}
std::vector<DWORD> Pixels(IDirect3DDevice9* d){IDirect3DSurface9 *rt=nullptr,*sys=nullptr;assert(SUCCEEDED(d->GetRenderTarget(0,&rt)));assert(SUCCEEDED(d->CreateOffscreenPlainSurface(64,64,D3DFMT_A8R8G8B8,D3DPOOL_SYSTEMMEM,&sys,nullptr)));assert(SUCCEEDED(d->GetRenderTargetData(rt,sys)));D3DLOCKED_RECT l{};assert(SUCCEEDED(sys->LockRect(&l,nullptr,D3DLOCK_READONLY)));std::vector<DWORD> v(4096);for(int y=0;y<64;y++)memcpy(v.data()+y*64,(char*)l.pBits+y*l.Pitch,256);sys->UnlockRect();rt->Release();sys->Release();return v;}
int main(int argc,char** argv){setvbuf(stdout,nullptr,_IONBF,0);assert(argc==2);auto original=ReadFile(argv[1]);auto old=Compile(original,"ps_3_0");auto cur=Compile(kWaterLampsHlsl,"ps_3_0");
for(auto b:{old,cur}){ID3DBlob* dis=nullptr;assert(SUCCEEDED(D3DDisassemble(b->GetBufferPointer(),b->GetBufferSize(),0,nullptr,&dis)));std::string s((char*)dis->GetBufferPointer(),dis->GetBufferSize());auto i=s.find("approximately");if(i!=std::string::npos)printf("Shader: %s\n",s.substr(i,s.find('\n',i)-i).c_str());dis->Release();}
auto d3d=Direct3DCreate9(D3D_SDK_VERSION);assert(d3d);auto w=CreateWindowExW(0,L"STATIC",L"Water lamp offline check",WS_POPUP,0,0,64,64,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);D3DPRESENT_PARAMETERS pp{};pp.Windowed=TRUE;pp.SwapEffect=D3DSWAPEFFECT_DISCARD;pp.BackBufferWidth=pp.BackBufferHeight=64;pp.BackBufferFormat=D3DFMT_A8R8G8B8;pp.hDeviceWindow=w;IDirect3DDevice9* d=nullptr;assert(SUCCEEDED(d3d->CreateDevice(0,D3DDEVTYPE_HAL,w,D3DCREATE_SOFTWARE_VERTEXPROCESSING,&pp,&d)));
IDirect3DPixelShader9 *psOld=nullptr,*psNew=nullptr;assert(SUCCEEDED(d->CreatePixelShader((DWORD*)old->GetBufferPointer(),&psOld)));assert(SUCCEEDED(d->CreatePixelShader((DWORD*)cur->GetBufferPointer(),&psNew)));
auto vs=Compile("struct O{float4 p:POSITION;float4 uv:TEXCOORD0;float4 world:TEXCOORD1;float4 fog:TEXCOORD3;};O main(float4 p:POSITION,float2 uv:TEXCOORD0){O o;o.p=p;o.uv=float4(uv,uv);o.world=float4(0,0,0,1);o.fog=0;return o;}","vs_3_0");IDirect3DVertexShader9* vshader=nullptr;assert(SUCCEEDED(d->CreateVertexShader((DWORD*)vs->GetBufferPointer(),&vshader)));D3DVERTEXELEMENT9 el[]={{0,0,D3DDECLTYPE_FLOAT4,D3DDECLMETHOD_DEFAULT,D3DDECLUSAGE_POSITION,0},{0,16,D3DDECLTYPE_FLOAT2,D3DDECLMETHOD_DEFAULT,D3DDECLUSAGE_TEXCOORD,0},D3DDECL_END()};IDirect3DVertexDeclaration9* decl=nullptr;assert(SUCCEEDED(d->CreateVertexDeclaration(el,&decl)));struct V{float x,y,z,w,u,v;};V tri[]={{-1,-1,.5,1,0,1},{-1,3,.5,1,0,-1},{3,-1,.5,1,2,1}};
IDirect3DTexture9* wave=nullptr;assert(SUCCEEDED(d->CreateTexture(1,1,1,0,D3DFMT_A8R8G8B8,D3DPOOL_MANAGED,&wave,nullptr)));D3DLOCKED_RECT l{};wave->LockRect(0,&l,nullptr,0);*(DWORD*)l.pBits=0xff0000ff;wave->UnlockRect(0);d->SetTexture(0,wave);d->SetTexture(1,wave);
d->SetVertexShader(vshader);d->SetVertexDeclaration(decl);d->SetRenderState(D3DRS_ZENABLE,FALSE);d->SetRenderState(D3DRS_CULLMODE,D3DCULL_NONE);d->SetRenderState(D3DRS_ALPHABLENDENABLE,FALSE);d->SetRenderState(D3DRS_COLORWRITEENABLE,7);
float c[60][4]{};c[1][1]=5;c[5][0]=c[5][1]=1;c[20][1]=5;c[20][3]=10;c[52][0]=1;c[53][0]=c[54][1]=c[55][2]=c[56][3]=1;
auto render=[&](IDirect3DPixelShader9* ps,bool filter,bool color){c[52][2]=filter;c[52][3]=color;d->SetPixelShader(ps);d->SetPixelShaderConstantF(0,&c[0][0],60);d->Clear(0,nullptr,D3DCLEAR_TARGET,0xff000000,1,0);assert(SUCCEEDED(d->BeginScene()));assert(SUCCEEDED(d->DrawPrimitiveUP(D3DPT_TRIANGLELIST,1,tri,sizeof(V))));assert(SUCCEEDED(d->EndScene()));return Pixels(d);};
int cases=0;for(float strength:{0.0f,0.1f,1.0f,3.0f}){c[36][0]=strength;c[36][1]=strength*.5f;c[36][2]=strength*.125f;auto baseline=render(psOld,false,false);auto legacy=render(psNew,false,false);for(int i=0;i<4096;i++){for(int shift:{0,8,16})assert(abs(int((baseline[i]>>shift)&255)-int((legacy[i]>>shift)&255))<=1);assert((legacy[i]>>24)==255);}cases++;
for(bool color:{false,true}){auto off=render(psNew,false,color);auto on=render(psNew,true,color);for(int i=0;i<4096;i++)assert(off[i]==on[i]);cases++;}auto preserved=render(psNew,true,true);if(strength==0)for(auto p:preserved)assert((p&0xffffff)==0);if(strength>=1){auto p=preserved[100];float red=(p>>16)&255,green=(p>>8)&255,blue=p&255;float rr=100.001f;float g=1-25/rr;float expected=strength*(.25f*2/(1+25/(rr*16))+.08f*g*g);if(expected>.7f){float excess=expected-.7f;expected=.7f+.1f*excess/(.1f+excess);}printf("Strength %.1f: RGB %.0f %.0f %.0f, expected red %.2f\n",strength,red,green,blue,255*expected);assert(abs(red-255*expected)<=1.5f);assert(red<=204);assert(abs(green-red*.5f)<=1.5f);assert(abs(blue-red*.125f)<=1.5f);} }
printf("PASS: old/new shaders compiled and created; %d flat-water A/B cases; legacy within 1 LSB, zero-light output, alpha and saturated color ratios\n",cases);
wave->Release();decl->Release();vshader->Release();vs->Release();psOld->Release();psNew->Release();old->Release();cur->Release();d->Release();d3d->Release();DestroyWindow(w);}
